src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\ORM\Mapping\JoinTable;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(
 * fields= {"email"},
 * message= "L'email que vous avez indiquez est déjà utilisé")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath = "password", message="Votre mot de passe doit être identique à celui entré au dessus")
     */
    public $confirm_password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $CP;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $portfolio;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $github;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pseudoGithub;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $CV;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $avatar;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $mobile;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $situation;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $mobileZone;

    /**
     * @ORM\OneToMany(targetEntity=Candidature::class, mappedBy="apprenant")
     */
    private $candidatures;

    /**
     * @ORM\ManyToMany(targetEntity=Competence::class, inversedBy="apprenant")
     */
    private $competences;

    /**
     * @ORM\ManyToOne(targetEntity=Promotion::class, inversedBy="apprenant")
     */
    private $promo;

    /**
     * @ORM\OneToMany(targetEntity=Annonce::class, mappedBy="entreprise")
     */
    private $annonces;

    public function __construct()
    {
        $this->candidatures = new ArrayCollection();
        $this->competences = new ArrayCollection();
        $this->annonces = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCP(): ?string
    {
        return $this->CP;
    }

    public function setCP(string $CP): self
    {
        $this->CP = $CP;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getPortfolio(): ?string
    {
        return $this->portfolio;
    }

    public function setPortfolio(string $portfolio): self
    {
        $this->portfolio = $portfolio;

        return $this;
    }

    public function getGithub(): ?string
    {
        return $this->github;
    }

    public function setGithub(string $github): self
    {
        $this->github = $github;

        return $this;
    }

    public function getPseudoGithub(): ?string
    {
        return $this->pseudoGithub;
    }

    public function setPseudoGithub(string $pseudoGithub): self
    {
        $this->pseudoGithub = $pseudoGithub;

        return $this;
    }

    public function getCV(): ?string
    {
        return $this->CV;
    }

    public function setCV(string $CV): self
    {
        $this->CV = $CV;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getMobile(): ?int
    {
        return $this->mobile;
    }

    public function setMobile(int $mobile): self
    {
        $this->mobile = $mobile;

        return $this;
    }

    public function getSituation(): ?int
    {
        return $this->situation;
    }

    public function setSituation(int $situation): self
    {
        $this->situation = $situation;

        return $this;
    }

    public function getMobileZone(): ?int
    {
        return $this->mobileZone;
    }

    public function setMobileZone(int $mobileZone): self
    {
        $this->mobileZone = $mobileZone;

        return $this;
    }

    /**
     * @return Collection|Candidature[]
     */
    public function getCandidatures(): Collection
    {
        return $this->candidatures;
    }

    public function addCandidature(Candidature $candidature): self
    {
        if (!$this->candidatures->contains($candidature)) {
            $this->candidatures[] = $candidature;
            $candidature->setApprenant($this);
        }

        return $this;
    }

    public function removeCandidature(Candidature $candidature): self
    {
        if ($this->candidatures->removeElement($candidature)) {
            // set the owning side to null (unless already changed)
            if ($candidature->getApprenant() === $this) {
                $candidature->setApprenant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Competence[]
     */
    public function getCompetences(): Collection
    {
        return $this->competences;
    }

    public function addCompetence(Competence $competence): self
    {
        if (!$this->competences->contains($competence)) {
            $this->competences[] = $competence;
            
        }

        return $this;
    }

    public function removeCompetence(Competence $competence): self
    {
        $this->competences->removeElement($competence);

        return $this;
    }


    public function eraseCredentials()
    {
        
    }
    public function getSalt()
    {
        
    }

    public function getPromo(): ?Promotion
    {
        return $this->promo;
    }

    public function setPromo(?Promotion $promo): self
    {
        $this->promo = $promo;

        return $this;
    }

    /**
     * @return Collection|Annonce[]
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonce $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->setEntreprise($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonce $annonce): self
    {
        if ($this->annonces->removeElement($annonce)) {
            // set the owning side to null (unless already changed)
            if ($annonce->getEntreprise() === $this) {
                $annonce->setEntreprise(null);
            }
        }

        return $this;
    }
}

src/Controller/UsersController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Competence;
use App\Entity\Entreprise;
use App\Form\InfoUserType;
use App\Entity\Candidature;
use App\Form\CompetenceType;
use App\Form\EntrepriseType;
use App\Form\CandidatureType;
use App\Form\UsersCompetenceType;
use App\Repository\UserRepository;
use App\Repository\AnnonceRepository;
use App\Repository\EntrepriseRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\CandidatureRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
/**
* @Route("/users", name="users_")
*/
class UsersController extends AbstractController
{
    
    /**
     * Information user
     * @Route("/infos/{id}", name="infoUser")
     */
    public function infosUser(Request $request, EntityManagerInterface $manager, User $user, AnnonceRepository $repoA): Response
    {
        $form = $this->createForm(InfoUserType::class, $user);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $manager->persist($user);
            $manager->flush();
        }
        return $this->render('users/index.html.twig', [
            'infoForm' => $form->createView(),
            'user' => $user,
            'annonces' => $repoA->findAll()
        ]);
    }

    /**
     * Ajout de nouvel compétences
     * @Route("/newSkill/{id}", name="skill")
     */
    public function newCompetences(Request $request, EntityManagerInterface $manager, User $user, AnnonceRepository $repoA){
        $form = $this->createForm(UsersCompetenceType::class, $user);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){         
            $manager->persist($user);
            $manager->flush();
            return $this->redirect($request->getUri());
        }

        $competence = new Competence();
        $formC = $this->createForm(CompetenceType::class, $competence);
        $formC->handleRequest($request);
        if($formC->isSubmitted() && $formC->isValid()){
            $manager->persist($competence);
            $manager->flush();
            return $this->redirect($request->getUri());
        }
        return $this->render('users/addSkill.html.twig', [
            'compForm' => $form->createView(),
            'addComp' => $formC->createView(),
            'annonces' => $repoA->findAll()
        ]);
    }

    /**
     * @Route("/entreprise", name="entreprise")
     */
    public function entreprise(Request $request, EntityManagerInterface $manager, EntrepriseRepository $repo, AnnonceRepository $repoA){
        $entreprise = new Entreprise();
        $form = $this->createForm(EntrepriseType::class, $entreprise);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $manager->persist($entreprise);
            $manager->flush();
            return $this->redirect($request->getUri());
        }


        return $this->render('users/entreprise.html.twig', [
            'entrepriseForm' => $form->createView(),
            'entreprises' => $repo->findAll(),
            'annonces' => $repoA->findAll()
        ]);
    }

    /**
     * @Route("/detailEntreprise/{id}", name="detailEntreprise")
     */
    public function detailEntreprise(EntrepriseRepository $repo, Entreprise $entreprise, AnnonceRepository $repoA){
        $entreprise->getId();
        return $this->render('users/detailEntreprise.html.twig', [
            'detailEntreprise' => $repo->find($entreprise),
            'annonces' => $repoA->findAll()
        ]);
    }

    /**
     * @Route("/candidature", name="candidature")
     */
    public function candidature(Request $request, EntityManagerInterface $manager, CandidatureRepository $repo, AnnonceRepository $repoA){
        $candidature = new Candidature();
        $form = $this->createForm(CandidatureType::class, $candidature);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $user = $this->getUser();
            $candidature->setApprenant($user);
            $manager->persist($candidature);
            $manager->flush();
            return $this->redirect($request->getUri());
        }
        $user = $this->getUser();
        $id = $user->getId();
        return $this->render('users/candidature.html.twig', [
            'candidatureForm' => $form->createView(),
            'candidatures' => $repo->findByExampleField($id),
            'annonces' => $repoA->findAll()
        ]);   
    }

    /**
     * @Route("/upCandidature/{id}", name="upCandidature")
     */
    public function upCandidature(Request $request, EntityManagerInterface $manager, Candidature $candidature, AnnonceRepository $repoA){
        $form = $this->createForm(CandidatureType::class, $candidature);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){         
            $manager->persist($candidature);
            $manager->flush();
            return $this->redirectToRoute('users_candidature');
        }

        return $this->render('users/upCandidature.html.twig', [
            'upCandidatureForm' => $form->createView(),
            'annonces' => $repoA->findAll()
        ]);
    }
}

templates/users/addSkill.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add Skill{% endblock %}

{% block body %}

{% if not app.user %} 

    <h2>Vous n'avez pas les droits</h2>
    <a href=" {{ path('security_login') }} "><button class="btn btn-primary">Connexion</button></a>

{% else %}
<div class="container cent">
    <div class="row cent justify-content-center align-items-center">
        <div class="col-12">
            <h2>Ajouts de nouvelles compétences</h2>
            {{ form_start(addComp) }}
                <div class="form-group">
                    {{form_row(addComp.nom, {'attr': {'class': 'form-control'}}) }}
                </div>
                <button type="submit" class="btn btn-success">Ajouter</button>
            {{ form_end(addComp) }}
        </div>
        <div class="col-12" style="margin-top:-200px">
            <h2>Mes Compétences:</h2>
            {{ form_start(compForm) }}
                <div class="form-group">
                    {{ form_row(compForm.competences, {'attr': {'class': 'form-control'}}) }}
                </div>
                <button type="submit" class="btn btn-success">Ajouter</button>
            {{ form_end(compForm) }}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/users/candidature.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes candidatures - EasyStage{% endblock %}

{% block body %}

{% if not app.user %} 

    <h2>Vous n'avez pas les droits</h2>
    <a href=" {{ path('security_login') }} "><button class="btn btn-primary">Connexion</button></a>

{% else %}
<div class="container centHeight">
    <div class="row centHeight justify-content-center align-items-center">
        <div class="col-12">
            <h2>Ajouter une candidature:</h2>
            {{ form_start(candidatureForm) }}
                <div class="form-group">
                    {{ form_row(candidatureForm.requestDate, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group">
                    {{ form_row(candidatureForm.relanceDate, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group">
                    {{ form_row(candidatureForm.meetingDate, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group">
                    {{ form_row(candidatureForm.status, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group">
                    {{ form_row(candidatureForm.entreprise, {'attr': {'class': 'form-control'}}) }}
                </div>
                <button type="submit" class="btn btn-success">Ajouter</button>
            {{ form_end(candidatureForm) }}
        </div>
        <div class="col-12">  
            <h2>Mes candidatures:</h2>

            <table class="table table-striped table-responsive-xl" >
                <thead>
                    <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Entreprise</th>
                    <th scope="col">Demande</th>
                    <th scope="col">Relance</th>
                    <th scope="col">RDV</th>
                    <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>
                
                    {% for candidature in candidatures %}
                        <tr>
                            {% if candidature.status == 0 %}  
                                <th scope="row">{{ candidature.id }}</th>
                            {% elseif candidature.status == 1 %}
                                <th scope="row" class="bg-warning">{{ candidature.id }}</th>
                            {% elseif candidature.status == 2 %}
                                <th scope="row" class="bg-success">{{ candidature.id }}</th>
                            {% elseif candidature.status == 3 %}
                                <th scope="row" class="bg-danger">{{ candidature.id }}</th>
                            {% endif %}
                            <td>{{ candidature.entreprise.nom }}</td>
                            <td>{{ candidature.requestDate|date('d/m/Y') }}</td>
                            {% if candidature.relanceDate == null %}
                                <td></td>
                            {% else %}
                                <td>{{ candidature.relanceDate|date('d/m/Y') }}</td>
                            {% endif %}
                            {% if candidature.meetingDate == null %}
                                <td></td>
                            {% else %}
                                <td>{{ candidature.meetingDate|date('d/m/Y') }}</td>
                            {% endif %}
                            {% if candidature.status == 0 %}
                                <td>En attente</td>
                            {% elseif candidature.status == 1 %}
                                <td>Relancée</td>
                            {% elseif candidature.status == 2 %}
                                <td>Positive</td>
                            {% elseif candidature.status == 3 %}
                                <td>Négative</td>
                            {% endif %}
                            <td><a href="{{ path('users_detailEntreprise', {'id': candidature.entreprise.id}) }}"><button class="btn btn-primary">Voir l'entreprise</button></a></td>
                            <td><a href="{{ path('users_upCandidature', {'id': candidature.id}) }}"><button class="btn btn-warning">Mettre à jour</button></a></td>
                        </tr>
                    {% else %}

                        <tr>
                            <td> Aucune candidature n'est enregistré pour vous dans la base de donnée</td>
                        </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/users/detailEntreprise.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ detailEntreprise.nom }} - détails{% endblock %}

{% block body %}
{% if not app.user %} 

    <h2>Vous n'avez pas les droits</h2>
    <a href=" {{ path('security_login') }} "><button class="btn btn-primary">Connexion</button></a>

{% else %}
<div class="container cent">
    <div class="row cent justify-content-center align-items-center">
        <div class="col-12 d-flex flex-column justify-content-center align-items-center">
            <h2>Détails de l'entreprise <span style="color:green;">{{ detailEntreprise.nom }}</span></h2>
            <h4><span class="text-info">Adresse: </span>{{ detailEntreprise.adresse }}</h4>
            <h4><span class="text-info">Code Postal: </span>{{ detailEntreprise.CP }}</h4>
            <h4><span class="text-info">Ville: </span>{{ detailEntreprise.ville }}</h4>
            <h4><span class="text-info">Téléphone: </span>{{ detailEntreprise.tel }}</h4>
            <h4><span class="text-info">E-mail: </span>{{ detailEntreprise.mail }}</h4>
            <a href="{{ detailEntreprise.website }}"><button class="btn btn-success">Voir le site</button></a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/users/entreprise.html.twig
{% extends 'base.html.twig' %}

{% block title %}Entreprise - EasyStage{% endblock %}

{% block body %}

{% if not app.user %} 

    <h2>Vous n'avez pas les droits</h2>
    <a href=" {{ path('security_login') }} "><button class="btn btn-primary">Connexion</button></a>

{% else %}
<div class="container centHeight">
    <div class="row centHeight justify-content-center align-items-center">
        <div class="col-12">
            <h2>Ajouter une entreprise:</h2>
            {{ form_start(entrepriseForm) }}
                <div class="form-group">
                    {{ form_row(entrepriseForm.nom, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group">
                    {{ form_row(entrepriseForm.adresse, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group">
                    {{ form_row(entrepriseForm.CP, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group">
                    {{ form_row(entrepriseForm.ville, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group">
                    {{ form_row(entrepriseForm.tel, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group">
                    {{ form_row(entrepriseForm.mail, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group">
                    {{ form_row(entrepriseForm.website, {'attr': {'class': 'form-control'}}) }}
                </div>
                <button type="submit" class="btn btn-success">Ajouter</button>
            {{ form_end(entrepriseForm) }}
        </div>
        <div class="col-12">
            <h2>Liste des entreprises:</h2>
            <table class="table table-striped" >
                <thead>
                    <tr>
                    <th scope="col">Id</th>
                    <th scope="col">nom</th>
                    <th scope="col">ville</th>
                    <th scope="col">website</th>
                    </tr>
                </thead>
                <tbody>
                    {% for entreprise in entreprises %}
                        <tr>  
                        <th scope="row">{{ entreprise.id }}</th>
                        <td>{{ entreprise.nom }}</td>
                        <td>{{ entreprise.ville }}</td>
                        <td><a href="{{ entreprise.website }}" target="_blank"><button class="btn btn-primary">Voir le site</button></a></td>
                        <td><a href="{{ path('users_detailEntreprise', {'id': entreprise.id}) }}"><button class="btn btn-warning">Détails</button></a></td>
                        </tr>
                    {% else %}

                        <tr>
                            <td> Aucune entreprises n'est enregistré dans la base de donnée</td>
                        </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/users/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ app.user.prenom }} - infos{% endblock %}

{% block body %}
{% if not app.user %} 

    <h2>Vous n'avez pas les droits</h2>
    <a href=" {{ path('security_login') }} "><button class="btn btn-primary">Connexion</button></a>

{% elseif app.user.id == user.id %}
<div class="container centHeight">
    <div class="row centHeight justify-content-center align-items-center">
        <div class="col-12">
            <h2>Bonjour <span style="color:green;">{{ app.user.prenom }}  {{ app.user.nom }}</span></h2>
            {{ form_start(infoForm) }}
                <div class="form-group">
                    {{ form_row(infoForm.username, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.email, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.nom, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.prenom, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.adresse, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.CP, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.Ville, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.tel, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.portfolio, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.github, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.pseudoGithub, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.CV, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.promo, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.avatar, {'attr': {'class': 'form-control upload', 'placeholder': 'Cliquez ici pour upload une image..'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.mobile, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.mobileZone, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.situation, {'attr': {'class': 'form-control'}}) }}
                </div>

                <div class="form-group">
                    {{ form_row(infoForm.competences, {'attr': {'class': 'form-control'}}) }}
                </div>

                <button type="submit" class="btn btn-warning">Mettre à jour</button>
            {{ form_end(infoForm) }}
        </div>
    </div>
</div>
{% else %}
<div class="container cent">
    <div class="row cent justify-content-center align-items-center">
        <div class="col-12">
            <div class="alert alert-success" role="alert">
                Silence is golden
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/users/upCandidature.html.twig
{% extends 'base.html.twig' %}

{% block title %} Update - Candidature {% endblock %}

{% block body %}
{% if not app.user %} 

    <h2>Vous n'avez pas les droits</h2>
    <a href=" {{ path('security_login') }} "><button class="btn btn-primary">Connexion</button></a>

{% else %}
<div class="container cent">
    <div class="row cent justify-content-center align-items-center">
        <div class="col-12">
            <h2>Bonjour <span style="color:green;">{{ app.user.prenom }}  {{ app.user.nom }}</span></h2>
            {{ form_start(upCandidatureForm) }}
                <div class="form-group">
                    {{ form_row(upCandidatureForm.entreprise, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group">
                    {{ form_row(upCandidatureForm.status, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group">
                    {{ form_row(upCandidatureForm.meetingDate, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group">
                    {{ form_row(upCandidatureForm.relanceDate, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="form-group">
                    {{ form_row(upCandidatureForm.requestDate, {'attr': {'class': 'form-control'}}) }}
                </div>
                <button type="submit" class="btn btn-warning">Mettre à jour</button>
            {{ form_end(upCandidatureForm) }}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}